### ISSUE TITLE
Problem with app connecting to account

### ISSUE THREAD

**Issue by Medafu** [jac0b-w/AlbumPaper#11]
I putted a http://localhost:8080/ in redirect URL blank and saved it, but after agreeing with app connection it just says that site can't be reached

**Comment by jac0b-w** [comment]
@Medafu 

Just to be clear
- the browser opened to accounts.spotify.com
- you pressed agree
- you were redirected to http://localhost:8080/ and got 'This site can’t be reached'

If this is the case someone had a [similar issue on reddit](https://www.reddit.com/r/truespotify/comments/oa8xyq/i_made_an_wallpaper_changer_app_that_connects_to/h3nvokv?utm_source=share&utm_medium=web2x&context=3) so it's likely that it has actually worked but the success page failed to show.
You can check if it worked if there is a `.cache` file where the application is installed (Program Files (x68) by default)

**Comment by Medafu** [comment]
![image](https://user-images.githubusercontent.com/43107510/124616267-9b703600-de7e-11eb-9f78-12bba5857dfa.png)
I'm redirected by programm here, click agree and get this:
![image](https://user-images.githubusercontent.com/43107510/124616441-bcd12200-de7e-11eb-9bbb-5b35449747eb.png)

**Comment by Medafu** [comment]
Also, there doesn't seem to be any .cache file. Gonna reboot my computer for test.

**Comment by Medafu** [comment]
Restarted pc and everything connected perfectly. Thanks for help.

**Comment by jac0b-w** [comment]
Thanks for the screenshots. Seems this is fixed by a restart I'll create a [spotipy](https://github.com/plamere/spotipy) issue and hopefully they can fix it properly :)
