### ISSUE TITLE
Can't Open Settings

### ISSUE THREAD

**Issue by oreece29** [jac0b-w/AlbumPaper#17]
For whatever reason I can't access settings when I launch the app. Any tips?

**Comment by jac0b-w** [comment]
Is it this context menu you're unable to access or is it the settings windows itself?

![image](https://user-images.githubusercontent.com/51512690/151719662-ef84df6e-0042-4bad-96dd-df56a0ee7c30.png)

**Comment by oreece29** [comment]
> 

The Window itself won't show up. If I click on the application, no window launches either. The window only showed up to set it up, but I am no longer able to access those settings.

**Comment by jac0b-w** [comment]
I would suggest killing AlbumPaper via task manager and starting it again. Failing that restart your pc. Some people seem to have issues on initial setup but a restart should fix it.

**Comment by oreece29** [comment]
Still no luck...any other tips?

**Comment by oreece29** [comment]
Wait I got it to work, thank you for your help! Sick app!

**Comment by jac0b-w** [comment]
If you know what you did please let me know :)
