### ISSUE TITLE
using last.fm gives "set a valid service" error

### ISSUE THREAD

**Issue by surasshu** [jac0b-w/AlbumPaper#23]
i just noticed theres a beta, but it has a notable last.fm issue:

using the last.fm API (with a confirmed valid key and correct name, as used in version 3.3) gives an error "set a valid service".

**Comment by jac0b-w** [comment]
I think you have updated from v3.3 to v4.0-beta.1 without completely deleting the files from 3.3 causing an issue.

You can either 
1. Just change the service name in settings.ini in the installation folder to `last.fm` (with the `.`)
2. completely delete the installation folder (default being C:\AlbumPaper) and reinstall

If you do decide option 2 please send me the `errors.log` file in issue #22 first

**Comment by surasshu** [comment]
sounds good! yeah i probably messed that up, whoops... just wanted to see if the bug was already fixed in 4.0 beta.1 so i could close the issue :)
